export { default as Message } from './Message'
export { default as TitleArea } from './TiltleArea'
export { default as ContentArea } from './ContentArea'
export { default as InputArea } from './InputArea'
export { default as Page } from './Page'
